apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-backend-2
  labels:
    commit-sha: COMMIT_SHA
    cloud.googleapis.com/location: australia-southeast1
  annotations:
    serving.knative.dev/creator: brannonwadforth@gmail.com
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: bmwadforth-dev@digital-node-1176.iam.gserviceaccount.com
      containers:
        - name: blog-backend-1
          image: GAR_IMAGE
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: WEB_TEMPLATE__PROJECTID
              value: digital-node-1176
            - name: WEB_TEMPLATE__FIRESTOREDATABASE
              value: bmwadforth-production
            - name: WEB_TEMPLATE__CLOUDSTORAGEBUCKET
              value: bmwadforth
            - name: WEB_TEMPLATE__CONTENTURL
              value: https://cdn.bmwadforth.com
            - name: WEB_TEMPLATE__GEMINISERVICE
              value: gemini-n6b4oskuua-ts.a.run.app:443
            - name: WEB_TEMPLATE__JWTSIGNINGKEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: WEB_TEMPLATE__JWTSIGNINGKEY
            - name: WEB_TEMPLATE__APIKEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: WEB_TEMPLATE__APIKEY
            - name: WEB_TEMPLATE__GEMINI_APIKEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: WEB_TEMPLATE__GEMINI_APIKEY
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
    - percent: 100
      revisionName: blog-backend-2-COMMIT_SHA