/**
 * @fileoverview gRPC-Web generated client stub for gemini_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.2
// source: gemini_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as gemini_service_pb from './gemini_service_pb';


export class GeminiClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorQueryGemini = new grpcWeb.MethodDescriptor(
    '/gemini_service.Gemini/QueryGemini',
    grpcWeb.MethodType.SERVER_STREAMING,
    gemini_service_pb.QueryRequest,
    gemini_service_pb.QueryResponse,
    (request: gemini_service_pb.QueryRequest) => {
      return request.serializeBinary();
    },
    gemini_service_pb.QueryResponse.deserializeBinary
  );

  queryGemini(
    request: gemini_service_pb.QueryRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<gemini_service_pb.QueryResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/gemini_service.Gemini/QueryGemini',
      request,
      metadata || {},
      this.methodDescriptorQueryGemini);
  }

}

