// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article": {
            "post": {
                "description": "Create article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Create article"
                ],
                "summary": "Create article",
                "parameters": [
                    {
                        "description": "Create article model object",
                        "name": "article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-string"
                        }
                    }
                }
            }
        },
        "/article/{articleId}/content": {
            "post": {
                "description": "Upload article content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload article content"
                ],
                "summary": "Upload article content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Article Identifier",
                        "name": "articleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-models_CreateArticleContentResponse"
                        }
                    }
                }
            }
        },
        "/article/{slug}": {
            "get": {
                "description": "Get article by slug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get article by slug"
                ],
                "summary": "Get article by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Article slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-models_ArticleModel"
                        }
                    }
                }
            }
        },
        "/articles": {
            "get": {
                "description": "Get articles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get articles"
                ],
                "summary": "Get articles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-array_models_ArticleModel"
                        }
                    }
                }
            }
        },
        "/gemini": {
            "get": {
                "description": "Query gemini",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query gemini"
                ],
                "summary": "Query gemini via gRPC",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "HealthCheck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "HealthCheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-controllers_HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login user"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login user model object",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "description": "Get user sessions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get user sessions"
                ],
                "summary": "Get user sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-models_UserSessionModel"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get user status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get user status"
                ],
                "summary": "Get user status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-models_UserStatusModel"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Create user"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "Create user model object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.ApiResponse-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "boolean"
                }
            }
        },
        "models.ArticleModel": {
            "description": "A model that describes an article",
            "type": "object",
            "properties": {
                "articleId": {
                    "type": "string"
                },
                "contentUrl": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "documentRef": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "models.CreateArticleContentResponse": {
            "type": "object",
            "properties": {
                "contentId": {
                    "type": "string"
                },
                "thumbnailId": {
                    "type": "string"
                }
            }
        },
        "models.CreateArticleRequest": {
            "description": "New article request",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.CreateUserRequest": {
            "description": "New user request",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.LoginUserRequest": {
            "description": "Login user request",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserSessionModel": {
            "description": "A model that describes a user session",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "loggedIn": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserStatusModel": {
            "description": "User status model",
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "loggedInSince": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-array_models_ArticleModel": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ArticleModel"
                    }
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-controllers_HealthCheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/controllers.HealthCheckResponse"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-models_ArticleModel": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.ArticleModel"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-models_CreateArticleContentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.CreateArticleContentResponse"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-models_UserSessionModel": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.UserSessionModel"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-models_UserStatusModel": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.UserStatusModel"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "util.ApiResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
