name: Build and Release
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bmwadforth-com'
          cache-dependency-path: './web/package-lock.json'
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build --build-arg NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }} . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest --tag australia-southeast2-docker.pkg.dev/digital-node-1176/bmwadforth-docker/${{ github.event.repository.name }}:latest
      - name: Push the Docker to GitHub
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
      - name: Push the Docker to GCP
        run: docker push australia-southeast2-docker.pkg.dev/digital-node-1176/bmwadforth-docker/${{ github.event.repository.name }}:latest