name: Swagger

on:
  push:
    branches:
      - main

jobs:
  swagger:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - name: Generate Swagger
        run: |
          docker pull quay.io/goswagger/swagger
          alias swagger='docker run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$(go env GOPATH):/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger'
          swagger generate spec -o ./artifacts/swagger.json

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./artifacts
          retention-days: 1