name: Swagger

on:
  push:
    branches:
      - main

jobs:
  swagger:
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'              

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./docs
          retention-days: 1